name: Publish to Expo CDN

on:
  push:
    branches:
      - develop
      - master

jobs:
  Publishing:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Cloning code
        uses: actions/checkout@v2

      - name: Installing node js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Installing expo cli
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Creating .env for development
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "${{ secrets.DEVELOPMENT_ENV_VARS }}" >> .env

      - name: Creating .env for staging
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.STAGING_ENV_VARS }}" >> .env

      - name: Installing dependencies
        run: npm ci

      - name: Publishing to development channel
        if: github.ref == 'refs/heads/develop'
        run: expo publish --release-channel development-v1

      - name: Publishing to staging channel
        if: github.ref == 'refs/heads/master'
        run: expo publish --release-channel staging-v1
